services:
  - type: web
    name: sistema-control-frontend
    env: static
    buildCommand: chmod +x build.sh && ./build.sh
    staticPublishPath: ./build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
